---
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# call needed  packages 
library(dplyr)
library(ggplot2)
library(readr)
library(stringr)
library(hrbrthemes)
library(colorblindr)
library(cowplot)
library(tinytex)

setwd("~/Dropbox/Funding applications/RStudio Internship/nfl_analysis")

#load data in better
data <- read_csv("data/nfl_2010-2017.csv") %>%                 # load data
  select(-X1)

data$team <- str_replace_all(data$team, c("JAC" = "JAX", "STL" = "LA", 
                                          "SD" = "LAC"))       # change team names if teams have moved

#condense individual data into yearly stats
indData <- data %>%
  select(-game_week) %>%                                       # remove irrelevant vars
  group_by(name, game_year, team) %>%                          # group by player and year 
  summarise_at(.vars = vars(-name, -team, -game_year, -position), 
               .funs = funs(sum), na.rm = TRUE) %>%            # sum all statistics and remove NAs
  ungroup()                                                    # ungroup

#add team variable back into individual data
indData <- data %>%
  select(name, position, team) %>%
  left_join(indData, by = c("name", "team"))

#condense team data into yearly stats
teamData <- data %>%
  filter(!is.na(team)) %>%                          # remove entries w/ NA team 
  select(-name, -position, -game_week, -rate) %>%   # remove irrelavant vars
  group_by(team, game_year) %>%                     # group by team and year
  summarise_all(funs(sum), na.rm = TRUE) %>%        # sum all statistics and remove NAs
  ungroup()                                         # ungroup
```

```{r, include = FALSE}
indData <- indData %>%                               # modify current data
  group_by(position, game_year) %>%                  # group by player and year
  mutate_at(vars(-name, -position, 
                 -game_year, -team),                 # unselect character vars
                                                     # and year var
            funs(z = ((. - mean(.)) / sd(.)))) %>%   # create z-score for all 
                                                     # variables

  ungroup() %>%                                      # ungroup
  select(name, position, game_year, contains("z"))   # restrict vars to zscores


rb <- indData %>%                                    # create dataset for RBs
  select(name, game_year, position, contains("rush")) %>% # select rushing vars
  filter(position == "RB") %>%                       # filter to RB position
  select(-position) %>%                              # remove position var
  mutate(rush_fumbles_z = rush_fumbles_z * -1) %>%   # reverse score fumbles
  ungroup() %>%                                      # clear any existing grouping
  group_by(name, game_year) %>%                      # group by player name
  mutate(totalZ = rush_att_z + rush_yds_z + rush_avg_z + rush_tds_z + 
              ifelse(is.na(rush_fumbles_z), 0, rush_fumbles_z)) %>%   # create total z score index
  select(name, game_year, totalZ) %>%                # select name, year, and totalZ
  distinct() %>%                                     # remove duplicate entries
  arrange(desc(totalZ))                              # arrange with greatest valuea at top

qb <- indData %>%                                    # create dataset for QBs
  select(name, position, game_year, contains("pass"), contains("int"), 
         contains("sck"), contains("rate")) %>%      # select passing vars
  filter(position == "QB") %>%                       # filter down to QB position
  select(-position) %>%                              # remove position var
  mutate(int_z_sumZ = int_z * -1,
         sck_z_sumZ = sck_z * -1,
         pass_fumbles_z = pass_fumbles_z * -1) %>%   # reverse score ints, scks, and fumbles
  ungroup() %>%                                      # clear any existing grouping
  group_by(name, game_year) %>%                      # group by player name
  mutate(totalZ = pass_att_z + pass_yds_z + pass_tds_z + int_z + sck_z + 
              ifelse(is.na(pass_fumbles_z), 0, pass_fumbles_z) + rate_z) %>%  # create total z score index
  select(name, game_year, totalZ) %>%                # select name, year and totalZ
  distinct() %>%                                     # remove duplicate entries
  arrange(desc(totalZ))                              # arrange with greatest valuea at top

wr_te <- indData %>%                                 # create dataset for WRs and TEs
  select(name, position, game_year, contains("rec")) %>% # select receiving vars
  filter(position == "WR/TE") %>%                    # filter down to wr/te
  select(-position) %>%                              # remove position var
  ungroup() %>%                                      # remove any existing groupings
  group_by(name, game_year) %>%                      # group by player name
  mutate(rec_fumbles_z = rec_fumbles_z * -1) %>%     # reverse score fumbles
  mutate(totalZ = rec_z + rec_yds_z + rec_avg_z + rec_tds_z + 
              ifelse(is.na(rec_fumbles_z), 0, rec_fumbles_z)) %>% # create total z score index
  select(name, game_year, totalZ) %>%                # select name, year, and totalZ
  distinct() %>%                                     # remove duplicate entries
  arrange(desc(totalZ))                              # arrange with greatest valuea at top

rbCareer <- rb %>%                                   # specify rb dataset
  ungroup() %>%                                      # remove previous groupings
  group_by(name) %>%                                 # group by name
  summarise(careerZ = sum(totalZ, na.rm = TRUE)) %>% # sum all zscores by person
  arrange(desc(careerZ))                             # arrange in a descending order
  
qbCareer <- qb %>%                                   # specify qb data
  ungroup() %>%                                      # remove previous groupings
  group_by(name) %>%                                 # group by name
  summarise(careerZ = sum(totalZ, na.rm = TRUE)) %>% # sum all zscores by person
  arrange(desc(careerZ))                             # arrange in a descending order

wr_teCareer <- wr_te %>%                             # specify wr_te data
  ungroup() %>%                                      # remove previous groupings
  group_by(name) %>%                                 # group by name
  summarise(careerZ = sum(totalZ, na.rm = TRUE)) %>% # sum all zscores by person
  arrange(desc(careerZ))                             # arrange in a descending order

rb                                                   # print rb

rbCareer                                             # print rb career data

qb                                                   # print qb

qbCareer                                             # print qb career data

wr_te                                                # print wr_te

wr_teCareer                                          # print wr_te career data
```


```{r include = FALSE}
teamData <- teamData %>%                             # modify current data
  group_by(game_year) %>%                            # group by player and year
  mutate_at(vars(-team, -game_year),                 # unselect character vars
                                                     # and year var
            funs(z = ((. - mean(., na.rm = TRUE)) / sd(., na.rm = TRUE)))) %>%   # create z-score for all 
                                                     # variables 

  ungroup() %>%                                      # ungroup
  select(team, game_year, contains("z")) %>%         # restrict vars to zscores
  group_by(team, game_year) %>%                      # group by name and position
  summarise_at(vars(-team, -game_year), funs(sumZ = sum(., na.rm = TRUE))) %>%    #sum zscores across years
  mutate(rush_fumbles_z_sumZ = rush_fumbles_z_sumZ * -1,
         rec_fumbles_z_sumZ = rec_fumbles_z_sumZ * -1,
         int_z_sumZ = int_z_sumZ * -1,
         sck_z_sumZ = sck_z_sumZ * -1,
         pass_fumbles_z_sumZ = pass_fumbles_z_sumZ * -1) %>% # reverse score fumbles, sacks, and ints
  mutate(totalZ = rush_att_z_sumZ + rush_yds_z_sumZ + rush_avg_z_sumZ + 
              rush_tds_z_sumZ + 
              ifelse(is.na(rush_fumbles_z_sumZ), 0, rush_fumbles_z_sumZ) + 
              rec_z_sumZ + 
              rec_yds_z_sumZ + rec_avg_z_sumZ + rec_tds_z_sumZ +
              rec_fumbles_z_sumZ + pass_att_z_sumZ + pass_yds_z_sumZ + 
              pass_tds_z_sumZ + int_z_sumZ + sck_z_sumZ + 
              pass_fumbles_z_sumZ) %>%               # create total z score index
  select(team, game_year, totalZ) %>%
  arrange(desc(totalZ))                              # sort in descending order

teamDataWindow <- teamData %>%                       # store teamData in teamDataWindow
  group_by(team) %>%                                 # group by team
  summarise(windowZ = sum(totalZ)) %>%               # sum z scores across team
  arrange(desc(windowZ))                             # arrange in descending order

teamData                                             # print teamData

teamDataWindow                                       # print teamDataWindow
```


```{r}
# graph individuals' season data
rb %>%
  ggplot(aes(x = game_year, y = totalZ)) +                                   # set vars for axis
  geom_jitter(alpha = 5/9, color = "green") +                                # set alpha and color
  theme(panel.background = element_rect(fill = 'black', colour = 'black'),   # set background to black
        panel.grid.major = element_blank(),                                  # remove major grid lines
        panel.grid.minor = element_blank()) +                                # remove minor grid lines
  ggtitle("RB Performance by Season") +                                      # set graph title
  labs(x = "Year", y = "Total Z Score")                                      # set axes labels

rb                                                                           # graph rb data

qb %>%
  ggplot(aes(x = game_year, y = totalZ)) +                                   # set vars for axis
  geom_jitter(alpha = 5/9, color = "green") +                                # set alpha and color
  theme(panel.background = element_rect(fill = 'black', colour = 'black'),   # set background to black
        panel.grid.major = element_blank(),                                  # remove major grid lines
        panel.grid.minor = element_blank()) +                                # remove minor grid lines
  ggtitle("QB Performance by Season") +                                      # set graph title
  labs(x = "Year", y = "Total Z Score")                                      # set axes labels

qb                                                                           # graph qb data

wr_te %>%
  ggplot(aes(x = game_year, y = totalZ)) +                                   # set vars for axis
  geom_jitter(alpha = 5/9, color = "green") +                                # set alpha and color
  theme(panel.background = element_rect(fill = 'black', colour = 'black'),   # set background to black
        panel.grid.major = element_blank(),                                  # remove major grid lines
        panel.grid.minor = element_blank()) +                                # remove minor grid lines
  ggtitle("WR/TE Performance by Season") +                                   # set graph title
  labs(x = "Year", y = "Total Z Score")                                      # set axes labels

wr_te                                                                        # graph wr_te data

# graph team data
teamData %>%
  ggplot(aes(x = game_year, y = totalZ, color = team)) +                     # set vars for axis
  geom_jitter(alpha = 5/9) +                                                 # set alpha
  theme(panel.background = element_rect(fill = 'black', colour = 'black'),   # set background to black
        panel.grid.major = element_blank(),                                  # remove major grid lines
        panel.grid.minor = element_blank()) +                                # remove minor grid lines
  ggtitle("Team Performance by Season") +                                    # set graph title
  labs(x = "Year", y = "Total Z Score")                                      # set axes labels

teamData                                                                     # graph team data
```